apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: rentzone-secret
  namespace: rentzone
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: <arn-of-the-secret-you-created-in-secret-manager>
          objectAlias: "app-secret"
